### ISSUE TITLE
Update Axis Variables

### ISSUE THREAD

**Issue by SevereOverfl0w** [roots-dev/base#12]
`_settings.styl` is no longer valid, due to variables being dollar prefixed in axis, e.g. `font-stack` -> `$font-stack`

**Comment by jenius** [comment]
Nice catch! Would you be willing to PR a fix for this? If not, one of us will take care of it soon, but you deserve the credit :grinning:

**Comment by SevereOverfl0w** [comment]
Absolutely no problem. Already on my to-do list, just wanted to make sure
there was a related report ASAP in case somebody ran into the same issue as
me.

**Comment by dbox** [comment]
copying over axis settings should to the trick.

**Comment by SevereOverfl0w** [comment]
Ah, Axis@latest no longer requires Nib, awesome.

Looks like I may have manually upgraded Axis on the project where this has occurred (I was going to try postcss, but decided not to).

Should the base be upgraded to Axis 0.5.x? Or should we just leave it on Axis 0.4.x and then keep the vars the same?

**Comment by dbox** [comment]
Yeah whenever this repo goes to axis 0.5.x we'll have to change the vars. No need for nib for new projects.

**Comment by SevereOverfl0w** [comment]
Wouldn't that mean a loss of functionality? I know Nib is rather annoying, *personally* I'll be removing it first thing, but I have no idea on actual use.

Is there any reason to not upgrade to Axis 0.5.x now? It's a few settings changing + package.json number bump.

**Comment by dbox** [comment]
No, we ported basically everything back into Axis. See more here: 
https://github.com/jenius/axis/pull/210#issuecomment-139811494

I think totally fine to go ahead and bump. It's time!

**Comment by SevereOverfl0w** [comment]
Excellent! I'll make the relevant commits now.

**Comment by dbox** [comment]
Great! Thanks for doing!

**Comment by SevereOverfl0w** [comment]
Continued in https://github.com/roots-dev/base/pull/13
