### ISSUE TITLE
Is there a way to bend paths?

### ISSUE THREAD

**Issue by FranzSkuffka** [roots-dev/base#8]
If so, roots could be used as more than a frontend-fullstack, for example as wordpress dev template etc.

**Comment by jenius** [comment]
I don't understand the question, or why it was filed on this repository...

**Comment by slang800** [comment]
I think @FranzSkuffka's asking if the paths are configurable so that roots could compile something like a WordPress theme from coffeescript/stylus/whatever.

And the paths are configurable now, so that should be possible, even though roots isn't really geared towards WP dev right now.

**Comment by FranzSkuffka** [comment]
Thank you. I just did not know where i could find the docs for v3. There we go.

**Comment by jenius** [comment]
They are still in progress, but you can find some at http://roots.netlify.com -- after public release this will be up at roots.cx :grinning:

**Comment by FranzSkuffka** [comment]
This is beyond awesome. Even my macbook thinks it's a jet when browsing this site.
:smile:
